name: My-CLI
on:
  push:




jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "Hello World"

  test:
    name: Test Python package
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Install package
        run: Run Pytest
        run: pytest -vv